// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4NpchbSz-ZzJMLzcHpXU4MANm0eXlDA',
    appId: '1:337910756528:web:77dcdc8a12112eacdff775',
    messagingSenderId: '337910756528',
    projectId: 'modern-erp-suite',
    authDomain: 'modern-erp-suite.firebaseapp.com',
    storageBucket: 'modern-erp-suite.firebasestorage.app',
    measurementId: 'G-VGQPETTS9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PMhxcD0l8TvMd0D9s0hcOPW4svuHmyY',
    appId: '1:337910756528:android:e3a7776c84c8cea4dff775',
    messagingSenderId: '337910756528',
    projectId: 'modern-erp-suite',
    storageBucket: 'modern-erp-suite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXXLTLackUcs3dOiWfcXooXiLRFBGwcs',
    appId: '1:337910756528:ios:1f737db51466a782dff775',
    messagingSenderId: '337910756528',
    projectId: 'modern-erp-suite',
    storageBucket: 'modern-erp-suite.firebasestorage.app',
    iosBundleId: 'com.example.eprSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXXLTLackUcs3dOiWfcXooXiLRFBGwcs',
    appId: '1:337910756528:ios:1f737db51466a782dff775',
    messagingSenderId: '337910756528',
    projectId: 'modern-erp-suite',
    storageBucket: 'modern-erp-suite.firebasestorage.app',
    iosBundleId: 'com.example.eprSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm4NpchbSz-ZzJMLzcHpXU4MANm0eXlDA',
    appId: '1:337910756528:web:725863521bf6168cdff775',
    messagingSenderId: '337910756528',
    projectId: 'modern-erp-suite',
    authDomain: 'modern-erp-suite.firebaseapp.com',
    storageBucket: 'modern-erp-suite.firebasestorage.app',
    measurementId: 'G-Q5S4JPXYDX',
  );
}
