// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZyvX33NXD9hd9p_RFDT3l0OOiBHWhwP0',
    appId: '1:89542425380:web:502744e1591c04d94e51b1',
    messagingSenderId: '89542425380',
    projectId: 'task-management-app-2e66e',
    authDomain: 'task-management-app-2e66e.firebaseapp.com',
    storageBucket: 'task-management-app-2e66e.firebasestorage.app',
    measurementId: 'G-0Z32Y9KFKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClausu1umd7XMICMom6cl--DvRr6DyMjE',
    appId: '1:89542425380:android:ea7adc58171a8a744e51b1',
    messagingSenderId: '89542425380',
    projectId: 'task-management-app-2e66e',
    storageBucket: 'task-management-app-2e66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzk1xj_PFbZibN1fEPMgMedToTOBzqTfE',
    appId: '1:89542425380:ios:847918ad1d6dac864e51b1',
    messagingSenderId: '89542425380',
    projectId: 'task-management-app-2e66e',
    storageBucket: 'task-management-app-2e66e.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzk1xj_PFbZibN1fEPMgMedToTOBzqTfE',
    appId: '1:89542425380:ios:847918ad1d6dac864e51b1',
    messagingSenderId: '89542425380',
    projectId: 'task-management-app-2e66e',
    storageBucket: 'task-management-app-2e66e.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZyvX33NXD9hd9p_RFDT3l0OOiBHWhwP0',
    appId: '1:89542425380:web:19e46822f7f063c14e51b1',
    messagingSenderId: '89542425380',
    projectId: 'task-management-app-2e66e',
    authDomain: 'task-management-app-2e66e.firebaseapp.com',
    storageBucket: 'task-management-app-2e66e.firebasestorage.app',
    measurementId: 'G-90649LNGZN',
  );
}
